import fs from 'fs';
import path from 'path';
import { DiaryIndex, type DiaryEntry } from '#/ui/diary-index';

export const metadata = {
  title: 'Diary',
};

function readTitle(file: string): string {
  try {
    const m = fs.readFileSync(file, 'utf8').match(/<title>([^<]*)<\/title>/i);
    return m ? m[1].trim() : '';
  } catch {
    return '';
  }
}

// The list is generated by scanning public/diary/ at build time, so adding a
// new piece is just dropping its HTML file in — no manual list to maintain.
// Convention: `<slug>.html` is the Japanese edition; an optional
// `<slug>-en.html` is its English edition.
function getEntries(): DiaryEntry[] {
  const dir = path.join(process.cwd(), 'public', 'diary');
  let files: string[] = [];
  try {
    files = fs.readdirSync(dir);
  } catch {
    return [];
  }
  return files
    .filter((f) => f.endsWith('.html') && !f.endsWith('-en.html'))
    .map((f) => {
      const slug = f.replace(/\.html$/, '');
      const enFile = path.join(dir, `${slug}-en.html`);
      const hasEn = fs.existsSync(enFile);
      const titleJa = readTitle(path.join(dir, f));
      return {
        slug,
        titleJa,
        titleEn: hasEn ? readTitle(enFile) : titleJa,
        hasEn,
        mtime: fs.statSync(path.join(dir, f)).mtimeMs,
      };
    })
    .sort((a, b) => b.mtime - a.mtime)
    .map(({ mtime, ...e }) => e);
}

export default function Page() {
  return <DiaryIndex entries={getEntries()} />;
}
